### ISSUE TITLE
Easly fixable build error. Sentinel build succes on Sonoma and Sequoia. 

### ISSUE THREAD

**Issue by perez987** [alienator88/Sentinel#12]
Good afternoon. Sentinel code expects a Buils folder in the project folder, it isn't created by default. So this error is launched:

`/Users/yo/Developer/Sentinel/Builds: No such file or directory`

Creaing the Buils folder manually fixes the error.

In addition to this and as an informative note I have tried to compile Sentinel on 13, 14 and 15.
You already know that on Ventura it does not compile well because of AlinFoundation.
On Sonoma and Sequoia it compiles well once the error in the Builds folder is resolved. Both systems have Xcode 16 but Ventura has Xcode 15, this is probably the cause of this behavior.

**Comment by alienator88** [comment]
That Builds folder has some private scripts and things I use to build my releases so I didn't add it to the repo.
You can probably just remove the Builds folder from the project sidebar, as it's not required to run the project at all.
The xcproject file probably has that Builds shortcut in there and it fails to load it since it doesn't exist on your end.
![image](https://github.com/user-attachments/assets/f273271b-c10d-433b-93f7-0d6b0ab6826d)

So you can either leave the Builds folder as you've left it now, or you can just remove it from the project completely.
