### ISSUE TITLE
v1.9 is not working in Sequoia 15.1.1

### ISSUE THREAD

**Issue by 5T33Z0** [alienator88/Sentinel#13]
Hi.

I just wanted to let you know that your current version 1.9 of Sentinel (the one which supposdly installs the configuration profile automatically) to disable Gatekeeper does not work in macOS 15.1.1. After hitting the switch to disable gatekeeper, it just jumps back to "red" after a few seconds.

On the other hand, version 1.6 - which requires users to install/enable the configuration profile manually – still works fine. So maybe it would be a good idea to bring the option to manually install the config profile back as a fallback.

Greetings

**Comment by alienator88** [comment]
Hi there. So Apple reversed the decision where they were preventing the use of the `spctl` command to enable/disable gatekeeper and require profiles instead.
So I updated the app back to work with the supported Apple way. If you're still on a version of Sequoia that hasn't been fixed and still requires profiles, I'd suggest staying on v1.6 for the time being until you update to latest macOS version. The recent updates of my app don't have the profiles anymore and I wasn't really looking to support that workaround long term if it wasn't needed anymore.

**Comment by alienator88** [comment]
Out of curiosity, after you attempt to disable gatekeeper with latest version of sentinel, do you not get the option in Privacy settings page to set it to Anywhere, which effectively disables gatekeeper at that point?

https://iboysoft.com/images/en-news/how-to-disable-gatekeeper-macos-sequoia/select-anywhere-in-security-settings.jpg

**Comment by 5T33Z0** [comment]
There was no notification pointing me towards changing that setting.

**Comment by alienator88** [comment]
Ah yeah, looks like the command only enables the option to select "Anywhere" in Privacy settings but doesn't turn it on automatically. It used to though.
I'll look into adding some instructions and maybe open the settings page after disabling gatekeeper.

**Comment by alienator88** [comment]
This is fixed in v2.0 which is now available.
Thank you for reporting this!

**Comment by mkonia** [comment]
There is no 'Anywhere' option in the 'Security' section under 'Privacy & Security' (macOS 15.2). Where _exactly_ should the option be found?

**Comment by alienator88** [comment]
Once you toggle Gatekeeper to Off position, you should have 3 options available instead of 2. I tested this on 3 operating systems and it seems to work fine for me.

Here's what it looks like on my end with Gatekeeper On:
![Screenshot 2024-12-19 at 10 51 14 AM](https://github.com/user-attachments/assets/247ec37c-1d41-4547-9ee2-605670c87e95)


And with Gatekeeper Off:
![Screenshot 2024-12-19 at 10 52 00 AM](https://github.com/user-attachments/assets/b95e75e8-96c8-49cf-a608-1db191921510)

**Comment by mkonia** [comment]
Strange: The whole thing only worked after the 5th or 6th attempt. Previously, the deactivation of Gatekeeper was reset after Sentinel was closed. In other words, after starting Sentinel, the Gatekeeper button was green again. However, it worked after all. Thank you very much!

**Comment by alienator88** [comment]
That is pretty odd 😂 
The gatekeeper in the OS will stay 'semi-enabled' in Sequoia until it's switched to "Anywhere". Even though it's semi-enabled, the `spctl` command will still report it as On.

All the other OS's below Sequoia don't behave this way, Apple are just tightening things up even more now with 3rd party apps.
So technically if you turn gatekeeper off via Sentinel, but you don't switch to "Anywhere" in the Settings, if you reopen Sentinel, it will see it as Gatekeeper enabled still since that's what the `spctl` command reports and will switch back to On in the Sentinel UI. It's a headache, but we don't really have other options today.

**Comment by 5T33Z0** [comment]
@alienator88 After enabling gatekeeper and deleting the prviously installed profile, I ran v2.0 to disable gatekeeper again and it is working as expected.
